import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/lib/color-variables.tsx';
import { ThemeProvider } from "@/components/theme-provider";
import { InjectUserClass } from "@/components/InjectUserClass";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Webshop poc vercel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="user"
            enableSystem
            disableTransitionOnChange
            themes={['dark', 'light', 'user']}
          >
             <InjectUserClass />
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
